### ISSUE TITLE
NaN in tox21 dataset labels

### ISSUE THREAD

**Issue by adamxyang** [untom/biutils#1]
I got numerous NaNs in y_tr when I use `biutils` to create a tox21 dataset, my code is:
```
import biutils
x_tr, y_tr, x_va, y_va = biutils.load_dataset('tox21')
```
Moreover, if I change all the NaNs to 0 using `np.nan_to_num(y_tr)`, more than a half of the rows in `y_tr` will just become all zeros. Is that an intrinsic issue of the dataset or something went wrong in biutils?

**Comment by untom** [comment]
Hi! No row should become entirely zero. If it did, then something has gone massively wrong (maybe the underlying Tox21 files that I access have changed)?

In any case, biutils isn't really maintained much. If you just want a way to access the Tox21 dataset, you can find it for download here: http://bioinf.jku.at/research/DeepTox/tox21.html (or at the original Tox21 challenge website).
